### ISSUE TITLE
Hi, I am not clear with the steps to run the benchmarks.  Could you please help me with elaborated sequence of steps to be followed to run this test. My setup details are : cpu: AMD FX 4100 quad core:: gpu: Ellesmere

### ISSUE THREAD

**Issue by luckynikki** [QCGPU/qcgpu-rust#3]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. `rustc 1.26.0-nightly`):
* Operating System and version:
* Hardware (e.g. CPU: Intel i5-6360U, GPU: Intel Iris Graphics 540, 8GB RAM)

**Comment by adamisntdead** [comment]
Hello, do you know which open cl device is which? This can usually be found with the clinfo command

**Comment by adamisntdead** [comment]
Ping @luckynikki
